services:
  grafana:
    container_name: grafana
    restart: on-failure
    image: grafana/grafana-oss
    ports:
      - "8080:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
  redis:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  db:
    image: postgres
    restart: on-failure
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: discord
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes:
  grafana_data:
  redis_data:
  db_data:
